// Light-DOM custom element that displays the page's last-modified date,
// sourced from the repo-root sitemap.xml (issue #410).
//
// Why fetch sitemap.xml at runtime rather than inject at build time:
// the lastmod value is computed from `git log` per page, so injecting it
// back into each HTML file would re-touch the file and create a feedback
// loop with its own lastmod. The sitemap is the single source of truth
// and is auto-regenerated by .github/workflows/format.yml on every PR.
//
// The sitemap.xml lives at the repo root, one directory up from
// course/ and lectures/ — using a relative URL keeps this working on
// both GitHub Pages (under /limerick-cobol/) and on `npm run serve`.
//
// Light DOM (no Shadow DOM) so course.css typography applies. Renders
// nothing if the fetch fails or no matching <loc> is found, so a broken
// sitemap can never break a lesson page.

class LastUpdated extends HTMLElement {
	connectedCallback() {
		const sitemapUrl = new URL("../sitemap.xml", window.location.href).toString();
		fetch(sitemapUrl)
			.then((response) => (response.ok ? response.text() : null))
			.then((xml) => {
				if (!xml) return;
				const lastmod = this._findLastmod(xml, window.location.pathname);
				if (!lastmod) return;
				this.innerHTML = `<p class="last-updated"><small>Last updated: <time datetime="${lastmod}">${lastmod}</time></small></p>`;
			})
			.catch(() => {
				// Silently no-op on parse/network failure.
			});
	}

	/**
	 * Find the <lastmod> for the URL whose pathname matches `pathname`.
	 * Compares the last two path segments (e.g. "course/Foo.html") so this
	 * works both on GitHub Pages (under /limerick-cobol/) and on a local
	 * dev server where the same file is served from /course/Foo.html.
	 * @param {string} xml
	 * @param {string} pathname
	 * @returns {string|null} ISO date (YYYY-MM-DD) or null
	 */
	_findLastmod(xml, pathname) {
		const key = this._suffixKey(pathname);
		if (!key) return null;
		const doc = new DOMParser().parseFromString(xml, "application/xml");
		if (doc.querySelector("parsererror")) return null;
		for (const url of doc.getElementsByTagName("url")) {
			const loc = url.getElementsByTagName("loc")[0]?.textContent || "";
			let locPath;
			try {
				locPath = new URL(loc).pathname;
			} catch (_) {
				continue;
			}
			if (this._suffixKey(locPath) === key) {
				return url.getElementsByTagName("lastmod")[0]?.textContent || null;
			}
		}
		return null;
	}

	/**
	 * Extract "dir/file.html" from a pathname; returns "" if there is no
	 * directory segment (e.g. "/index.html" → "").
	 */
	_suffixKey(pathname) {
		const segments = pathname.split("/").filter(Boolean);
		if (segments.length < 2) return "";
		return segments.slice(-2).join("/");
	}
}

customElements.define("last-updated", LastUpdated);
