#!/usr/bin/env node
/**
 * inject-cross-links.ts
 *
 * Reads scripts/cross-links.json and inserts (or replaces) a <related-content>
 * block in every exercise leaf page listed in `files`. Also ensures the
 * related-content.js script tag is present in <head>.
 *
 * Phase 3 of Issue #220 (#254): bidirectional cross-links from exercises back
 * to course lessons (and to matching example programs).
 *
 * Examples are NOT processed here — they are fully regenerated by
 * scripts/build-examples.ts, which reads the same cross-links.json. Running
 * this script over an example would race with that build step.
 *
 * Usage:
 *   tsx scripts/inject-cross-links.ts
 *
 * Idempotent: re-running over already-injected files replaces the block in
 * place. Pretty-format with `biome format --write` afterwards.
 */

import fs from "fs";
import path from "path";

import { readJson } from "./lib/json.js";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const CROSS_LINKS_PATH = path.join(__dirname, "cross-links.json");
const MAX_ITEMS_PER_GROUP = 4;

/** A pair of [relative href, link title] as stored in cross-links.json. */
type CrossLink = [href: string, title: string];

interface CrossLinkFamily {
	lectures?: CrossLink[];
	examples?: CrossLink[];
	exercises?: CrossLink[];
}

interface CrossLinksData {
	files: Record<string, string[]>;
	families: Record<string, CrossLinkFamily>;
	pairs: Record<string, CrossLink>;
}

interface PageLinks {
	lectures: CrossLink[];
	examples: CrossLink[];
	exercises: CrossLink[];
}

const data = readJson<CrossLinksData>(CROSS_LINKS_PATH);

function resolvePageLinks(filePath: string): PageLinks {
	const familyNames = data.files[filePath] || [];
	const pair = data.pairs[filePath] || null;

	const lectureSet = new Map<string, string>();
	const exampleSet = new Map<string, string>();
	const exerciseSet = new Map<string, string>();

	const accumulate = (set: Map<string, string>, items?: CrossLink[]) => {
		for (const [href, title] of items || []) {
			if (href === filePath) continue;
			if (!set.has(href)) set.set(href, title);
		}
	};

	for (const familyName of familyNames) {
		const family = data.families[familyName];
		if (!family) {
			throw new Error(`Unknown family "${familyName}" referenced by ${filePath}`);
		}
		accumulate(lectureSet, family.lectures);
		accumulate(exampleSet, family.examples);
		accumulate(exerciseSet, family.exercises);
	}

	// Exm/Prg pairs go at the front of the examples list so they appear first.
	if (pair) {
		const [pairHref, pairTitle] = pair;
		const merged = new Map<string, string>([[pairHref, pairTitle]]);
		for (const [href, title] of exampleSet) {
			if (href !== pairHref) merged.set(href, title);
		}
		return {
			lectures: capList(lectureSet, filePath),
			examples: capList(merged, filePath),
			exercises: capList(exerciseSet, filePath),
		};
	}

	return {
		lectures: capList(lectureSet, filePath),
		examples: capList(exampleSet, filePath),
		exercises: capList(exerciseSet, filePath),
	};
}

function capList(map: Map<string, string>, filePath: string): CrossLink[] {
	const out: CrossLink[] = [];
	for (const [href, title] of map) {
		if (href === filePath) continue;
		out.push([href, title]);
		if (out.length >= MAX_ITEMS_PER_GROUP) break;
	}
	return out;
}

function toRelativeHref(fromFile: string, toFile: string): string {
	const fromDir = path.dirname(path.join(REPO_ROOT, fromFile));
	const toAbs = path.join(REPO_ROOT, toFile);
	const rel = path.relative(fromDir, toAbs);
	return rel.replaceAll(path.sep, "/");
}

function formatGroupAttribute(fromFile: string, items: CrossLink[]): string {
	return items.map(([href, title]) => `${toRelativeHref(fromFile, href)}|${title}`).join(", ");
}

function buildRelatedContentMarkup(filePath: string, links: PageLinks): string | null {
	const attrs: string[] = [];
	if (links.lectures.length) attrs.push(`lectures="${formatGroupAttribute(filePath, links.lectures)}"`);
	if (links.examples.length) attrs.push(`examples="${formatGroupAttribute(filePath, links.examples)}"`);
	if (links.exercises.length) attrs.push(`exercises="${formatGroupAttribute(filePath, links.exercises)}"`);
	if (!attrs.length) return null;
	return `<related-content\n\t${attrs.join("\n\t")}\n></related-content>`;
}

function ensureScriptTag(html: string, filePath: string): string {
	if (html.includes("components/related-content.js")) return html;

	const depth = filePath.split("/").length - 1; // examples/Foo/Bar.html → depth 2
	const prefix = "../".repeat(depth);
	const scriptTag = `\t\t<script src="${prefix}components/related-content.js" defer></script>\n`;

	// Insert just before </head>. Match the leading whitespace of the line so
	// the new tag aligns with its neighbours.
	const headCloseMatch = html.match(/^([ \t]*)<\/head>/m);
	if (!headCloseMatch) {
		throw new Error(`No </head> found in ${filePath}`);
	}
	const indent = headCloseMatch[1];
	return html.replace(
		headCloseMatch[0],
		`${scriptTag.replace(/\t\t/g, indent === "" ? "" : indent)}${headCloseMatch[0]}`,
	);
}

const EXISTING_BLOCK_RE = /<related-content\b[\s\S]*?<\/related-content>/;

function injectOrReplace(html: string, markup: string, filePath: string): string {
	if (EXISTING_BLOCK_RE.test(html)) {
		return html.replace(EXISTING_BLOCK_RE, markup);
	}

	// No existing block. Insert just before the matching </page-hero> closer.
	// Most pages have <page-hero ...></page-hero> followed by an <hr />; we
	// place the block just after the page-hero so it appears prominently at
	// the top of the page above the long code/spec content.
	const heroCloseMatch = html.match(/<\/page-hero>\s*(\r?\n)([ \t]*)/);
	if (!heroCloseMatch) {
		throw new Error(`Cannot find <page-hero> insertion point in ${filePath}`);
	}
	const newline = heroCloseMatch[1];
	const indent = heroCloseMatch[2];
	const replacement = `</page-hero>${newline}${indent}${markup}${newline}${indent}`;
	return html.replace(/<\/page-hero>\s*(\r?\n)([ \t]*)/, replacement);
}

let touched = 0;
let skipped = 0;
const errors: string[] = [];

for (const filePath of Object.keys(data.files)) {
	if (!filePath.startsWith("exercises/")) continue;
	const absPath = path.join(REPO_ROOT, filePath);
	if (!fs.existsSync(absPath)) {
		errors.push(`Missing file: ${filePath}`);
		continue;
	}

	const links = resolvePageLinks(filePath);
	const markup = buildRelatedContentMarkup(filePath, links);
	if (!markup) {
		skipped++;
		continue;
	}

	let html = fs.readFileSync(absPath, "utf8");
	const before = html;
	html = ensureScriptTag(html, filePath);
	try {
		html = injectOrReplace(html, markup, filePath);
	} catch (err) {
		errors.push(`${filePath}: ${(err as Error).message}`);
		continue;
	}

	if (html !== before) {
		fs.writeFileSync(absPath, html);
		touched++;
	} else {
		skipped++;
	}
}

console.log(`Touched ${touched} file(s); skipped ${skipped}.`);
if (errors.length) {
	console.error("\nErrors:");
	for (const e of errors) console.error("  " + e);
	process.exit(1);
}
